const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    DATA_EDITED: "PROFILE_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },

  posts: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    DATA_CREATED: "PROFILE_DATA_CREATED",
    DATA_EDITED: "PROFILE_DATA_EDITED",
    DATA_DELETED: "PROFILE_DATA_DELETED",
  },
};

export default actions;
